version: '2'
services :
  web :
    container_name: ocsinventory-server
    build : .
    links :
      - db
    ports :
      - 80:80
      - 443:443

  db :
    container_name: ocsinventory-db
    image : mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocs
      MYSQL_DATABASE : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdb:/var/lib/mysql
    ports :
      - 3306:3306

volumes:
  ocsdb:
